server:  port: 8888
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/student?useUnicode=ture&characterEncoding=UTF-8&serverTimezone=GMT%2B8&allowMultiQueries=true # allowMultiQueries使MySQL支持一次发送多条语句
    username: root
    password: 1314
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:      initial-size: 5 # 初始大小
      min-idle: 1 # 最小连接数
      max-active: 5 # 最大连接数
      max-wait: 60000 # 最大等待时间  mvc:    static-path-pattern: /static/**
  thymeleaf:    mode: HTML
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    cache: false
mybatis:  mapper-locations: classpath:mybatis/*.xml  typeAliasesPackage : com.*.entity # 指定包别名  configuration :    map-underscore-to-camel-case : true # 带有下划线的表字段映射为驼峰格式的实体类属性
    jdbc-type-for-null: NULL # null值处理，Oracle中Other类型会报错   #executor-type: batch # 批量操作    #pagehelperpagehelper:  helperDialect: mysql # 指定数据库方言  reasonable: true # 分页合理化 小于等于0显示第一页  ；大于等于最大显示最后一页  supportMethodsArguments: true # 支持通过 Mapper 接口参数来传递分页参数  params: count=countSql # 为了支持startPage(Object params)方法，增加了该参数来配置参数映射，用于从对象中根据属性名取值    
logging:  level:    root: info
    com.ran.mapper: trace
  pattern:    console: '%d{yyy-MM-dd} [%thread] %-5level %logger{50} - %msg%p%m%n'    
    